
server:
  port: 8086
management:
  security:
    enabled: false

spring:
  application:
    name: zuul-proxy
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.int}
zuul:
  routes:
    employee:
      path: /employee/**
      serviceId: employee-service
    payment:
      path: /payment/**
      serviceId: payment-service
    auth:
      path: /oauth/**
      serviceId: auth-server
security:
  oauth2:
    client:
      clientId: var
      clientSecret: var
    resource:
      userInfoUri: http://localhost:9000/user
      tokenInfoUri: http://localhost:9000/services/oauth/check_token
